# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W2cU8wk8m5PELQtpocaFwM0M9zN29Aho
"""

x=int(input("1-Sonni kiriting(x): "))
y=int(input("2-Sonni kiriting(y): "))

min=(x+y)/2
max=2*x*y

if x<y:
    x,y=min,max
elif x>y:
    x,y=max,min
print(x,y)