# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cZ8x8iYXR97itJzTfNO_6F4_b062scPk

# **Sonlarni kichigini topish**
"""

a = int(input("1-Sonni kiriting: "))
b = int(input("2-Sonni kiriting: "))
c = int(input("3-Sonni kiriting: "))

if a<b and a<c:
    print(a)
elif b<a and b<c:
    print(b)
else:
    print(c)